grasp_reward:
  _target_: isaaclab.managers.RewardTermCfg
  func: gear_sonic.envs.manager_env.mdp:reward_grasp
  weight: 1.0
  params:
    sensor_cfg:
      _target_: isaaclab.managers.SceneEntityCfg
      name: "object_to_hand_contact_sensor"
    contact_threshold: 0.1
    min_contacts: 3
    hand: "right_hand"
    command_name: "motion"
