hand_object_transform_6d:
  _target_: isaaclab.managers.ObservationTermCfg
  func: gear_sonic.envs.manager_env.mdp:hand_object_transform_6d
  params:
    asset_cfg:
      _target_: isaaclab.managers.SceneEntityCfg
      name: "object_to_hand_frame_transformer"
